# Generated by Django 3.0.2 on 2020-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200108_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordination',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
