# Generated by Django 3.0.2 on 2020-01-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_weddingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-01-13'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-01-13'),
        ),
    ]
