# Generated by Django 3.0.2 on 2020-01-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200113_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingday',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='weddingday',
            name='time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
