# Generated by Django 3.0.2 on 2020-01-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_wed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='partner1_email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='partner1_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='', editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='wedding',
            name='partner2_email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='partner2_gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='', editable=False, max_length=6),
        ),
    ]
