# Generated by Django 3.0.2 on 2020-01-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=70)),
                ('invited_by', models.CharField(blank=True, max_length=250, null=True)),
                ('save_the_date', models.CharField(blank=True, max_length=250, null=True)),
                ('invitation', models.CharField(blank=True, max_length=250, null=True)),
                ('response', models.CharField(blank=True, max_length=250, null=True)),
                ('attending', models.CharField(blank=True, max_length=250, null=True)),
                ('children', models.CharField(blank=True, max_length=250, null=True)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=500, null=True)),
                ('table_number', models.CharField(blank=True, max_length=250, null=True)),
                ('gift_description', models.CharField(blank=True, max_length=250, null=True)),
                ('thank_you_sent', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
